[2022-10-07 17:17:18,755] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_rappers_dag.load_rappers manual__2022-10-07T17:17:09.988688+00:00 [queued]>
[2022-10-07 17:17:18,788] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_rappers_dag.load_rappers manual__2022-10-07T17:17:09.988688+00:00 [queued]>
[2022-10-07 17:17:18,788] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-07 17:17:18,788] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-07 17:17:18,788] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-07 17:17:18,897] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): load_rappers> on 2022-10-07 17:17:09.988688+00:00
[2022-10-07 17:17:18,972] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_rappers_dag', 'load_rappers', 'manual__2022-10-07T17:17:09.988688+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/load_rappers_dag.py', '--cfg-path', '/tmp/tmpdftkw8ba', '--error-file', '/tmp/tmpwznl3doh']
[2022-10-07 17:17:18,965] {standard_task_runner.py:52} INFO - Started process 1511 to run task
[2022-10-07 17:17:18,991] {standard_task_runner.py:80} INFO - Job 2: Subtask load_rappers
[2022-10-07 17:17:20,532] {task_command.py:369} INFO - Running <TaskInstance: load_rappers_dag.load_rappers manual__2022-10-07T17:17:09.988688+00:00 [running]> on host 84650b6b2dfc
[2022-10-07 17:17:22,658] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_rappers_dag
AIRFLOW_CTX_TASK_ID=load_rappers
AIRFLOW_CTX_EXECUTION_DATE=2022-10-07T17:17:09.988688+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-07T17:17:09.988688+00:00
[2022-10-07 17:17:22,668] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-10-07 17:17:22,677] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python ${AIRFLOW_HOME}/scripts/load_rappers.py']
[2022-10-07 17:17:22,772] {subprocess.py:85} INFO - Output:
[2022-10-07 17:19:02,756] {subprocess.py:92} INFO - Compiling artist list...
[2022-10-07 17:19:02,798] {subprocess.py:92} INFO - Loading artists...
[2022-10-07 17:19:02,798] {subprocess.py:92} INFO - Traceback (most recent call last):
[2022-10-07 17:19:02,798] {subprocess.py:92} INFO -   File "/opt/***/scripts/load_rappers.py", line 82, in <module>
[2022-10-07 17:19:02,798] {subprocess.py:92} INFO -     main()
[2022-10-07 17:19:02,798] {subprocess.py:92} INFO -   File "/opt/***/scripts/load_rappers.py", line 74, in main
[2022-10-07 17:19:02,799] {subprocess.py:92} INFO -     dfRappers = get_artist_data(lister, combinedArtists)
[2022-10-07 17:19:02,799] {subprocess.py:92} INFO -   File "/opt/***/scripts/load_rappers.py", line 43, in get_artist_data
[2022-10-07 17:19:02,799] {subprocess.py:92} INFO -     dfRappers = pd.DataFrame(lister.pull_artist_data(combinedArtists))
[2022-10-07 17:19:02,799] {subprocess.py:92} INFO -   File "/opt/***/scripts/artist_lister.py", line 50, in pull_artist_data
[2022-10-07 17:19:02,799] {subprocess.py:92} INFO -     enrichedDict['popularity'].append(payload['popularity'])
[2022-10-07 17:19:02,799] {subprocess.py:92} INFO - KeyError: 'popularity'
[2022-10-07 17:19:04,771] {subprocess.py:96} INFO - Command exited with return code 1
[2022-10-07 17:19:06,564] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-10-07 17:19:07,034] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=load_rappers_dag, task_id=load_rappers, execution_date=20221007T171709, start_date=20221007T171718, end_date=20221007T171906
[2022-10-07 17:19:08,366] {standard_task_runner.py:97} ERROR - Failed to execute job 2 for task load_rappers (Bash command failed. The command returned a non-zero exit code 1.; 1511)
[2022-10-07 17:19:08,443] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-07 17:19:09,007] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
