[2022-10-07 17:19:01,878] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_rappers_dag.load_rappers scheduled__2022-10-05T15:00:00+00:00 [queued]>
[2022-10-07 17:19:01,899] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_rappers_dag.load_rappers scheduled__2022-10-05T15:00:00+00:00 [queued]>
[2022-10-07 17:19:01,899] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-07 17:19:01,899] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-07 17:19:01,899] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-07 17:19:01,945] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): load_rappers> on 2022-10-05 15:00:00+00:00
[2022-10-07 17:19:01,952] {standard_task_runner.py:52} INFO - Started process 1739 to run task
[2022-10-07 17:19:01,956] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_rappers_dag', 'load_rappers', 'scheduled__2022-10-05T15:00:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/load_rappers_dag.py', '--cfg-path', '/tmp/tmpvtsaru0p', '--error-file', '/tmp/tmpwwu3wzra']
[2022-10-07 17:19:01,964] {standard_task_runner.py:80} INFO - Job 19: Subtask load_rappers
[2022-10-07 17:19:02,154] {task_command.py:369} INFO - Running <TaskInstance: load_rappers_dag.load_rappers scheduled__2022-10-05T15:00:00+00:00 [running]> on host 84650b6b2dfc
[2022-10-07 17:19:02,461] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_rappers_dag
AIRFLOW_CTX_TASK_ID=load_rappers
AIRFLOW_CTX_EXECUTION_DATE=2022-10-05T15:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-05T15:00:00+00:00
[2022-10-07 17:19:02,463] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-10-07 17:19:02,466] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python ${AIRFLOW_HOME}/scripts/load_rappers.py']
[2022-10-07 17:19:02,505] {subprocess.py:85} INFO - Output:
[2022-10-07 17:19:09,406] {subprocess.py:92} INFO - Compiling artist list...
[2022-10-07 17:19:09,407] {subprocess.py:92} INFO - Traceback (most recent call last):
[2022-10-07 17:19:09,407] {subprocess.py:92} INFO -   File "/opt/***/scripts/load_rappers.py", line 82, in <module>
[2022-10-07 17:19:09,407] {subprocess.py:92} INFO -     main()
[2022-10-07 17:19:09,407] {subprocess.py:92} INFO -   File "/opt/***/scripts/load_rappers.py", line 73, in main
[2022-10-07 17:19:09,407] {subprocess.py:92} INFO -     combinedArtists = compile_artists(lister, genreDict, playlistDict)
[2022-10-07 17:19:09,407] {subprocess.py:92} INFO -   File "/opt/***/scripts/load_rappers.py", line 38, in compile_artists
[2022-10-07 17:19:09,407] {subprocess.py:92} INFO -     return lister.combine_artists(genreDict, playlistDict)
[2022-10-07 17:19:09,407] {subprocess.py:92} INFO -   File "/opt/***/scripts/artist_lister.py", line 38, in combine_artists
[2022-10-07 17:19:09,407] {subprocess.py:92} INFO -     artistDict = self.union_dict(artistDict, self.parse_search(k, v))
[2022-10-07 17:19:09,407] {subprocess.py:92} INFO -   File "/opt/***/scripts/artist_lister.py", line 16, in parse_search
[2022-10-07 17:19:09,408] {subprocess.py:92} INFO -     for i in range(len(payload['artists']['items'])):
[2022-10-07 17:19:09,408] {subprocess.py:92} INFO - KeyError: 'artists'
[2022-10-07 17:19:09,672] {subprocess.py:96} INFO - Command exited with return code 1
[2022-10-07 17:19:09,731] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-10-07 17:19:09,741] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=load_rappers_dag, task_id=load_rappers, execution_date=20221005T150000, start_date=20221007T171901, end_date=20221007T171909
[2022-10-07 17:19:09,807] {standard_task_runner.py:97} ERROR - Failed to execute job 19 for task load_rappers (Bash command failed. The command returned a non-zero exit code 1.; 1739)
[2022-10-07 17:19:09,832] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-07 17:19:09,908] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
